<?php
// This file generated by Propel 1.6.7 convert-conf target
return array (
  'app\\Models\\User' => 'app/Models/User.php',
  'app\\Models\\UserPeer' => 'app/Models/UserPeer.php',
  'app\\Models\\UserQuery' => 'app/Models/UserQuery.php',
  'app\\Models\\map\\UserTableMap' => 'app/Models/map/UserTableMap.php',
  'app\\Models\\om\\BaseUser' => 'app/Models/om/BaseUser.php',
  'app\\Models\\om\\BaseUserPeer' => 'app/Models/om/BaseUserPeer.php',
  'app\\Models\\om\\BaseUserQuery' => 'app/Models/om/BaseUserQuery.php',
);